import axios from 'axios';
window.axios = axios;

window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
window.axios.defaults.withCredentials = true;

// Axios will automatically extract the XSRF-TOKEN cookie 
// that is generated by the Sanctum stateful backend on first request.
window.axios.defaults.withCredentials = true;
window.axios.defaults.withXSRFToken = true;
